### ISSUE TITLE
add tutorial about how to report a bug

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku-website#7]
and then we should add the link to our app later

**Comment by neighborhood999** [comment]
See: https://github.com/neighborhood999/Kaku-website/blob/docs/docs/how-to-report-the-bug.md
We can discuss where content need fix. :laughing:

**Comment by EragonJ** [comment]
@neighborhood999 looks awesome ! Feel free to send me PR and I can merge that as the first step !

**Comment by neighborhood999** [comment]
@EragonJ I already send PR. done！

**Comment by EragonJ** [comment]
Merged !! Thanks a lot !! I think we can start to build up codegen process to generate HTML from Markdown and also, I think we can add Chinese version because we are from Taiwan XDDD

**Comment by EragonJ** [comment]
I'll close this bug first but we can still discuss below. Thanks again !!

**Comment by EragonJ** [comment]
And congratulate for your first solved bug in Kaku XDD :fireworks:

**Comment by neighborhood999** [comment]
@EragonJ Thank you HAHA！ I will do my best.
I will complete left over issue, and send PR for you. :laughing:

**Comment by EragonJ** [comment]
@neighborhood999 ++++ we can discuss more about how to do next ;P
