### ISSUE TITLE
Add link to AUR package for arch

### ISSUE THREAD

**Issue by forivall** [EragonJ/Kaku-website#8]
I uploaded a package for Kaku to the AUR for archlinux

https://aur4.archlinux.org/packages/kaku-bin/

It might be helpful for anyone who wants to make packages for other distributions.

**Comment by EragonJ** [comment]
Hey @forivall, thanks for adding this to the site. But I am curious how it can be autoupdated based on our releases ? Or this should be done manually ?

**Comment by forivall** [comment]
Unfortunately, it has to be done manually, in that, it would be too much of a hassle to automate.

P.S. Don't put spaces before question marks. It's considered poor style.

**Comment by EragonJ** [comment]
ok, i think i'll add one more link for this and if anyone is interested in this, they can just click the link and check it.

**Comment by EragonJ** [comment]
hey @forivall, I just added the link for AUR package. Just want to let you know that I don't have time and no arch linux either to test and maintain that. So if you have time, feel free to update it manually or ask for helps from the others !

Thanks again !
